name: Deploy YPS Theme to Azure via FTPS

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  web-deploy:
    name: 🎉 Deploy Theme Files to Azure
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4

      - name: 📂 Sync Theme to Azure FTPS
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /site/wwwroot/wp-content/themes/yps-theme/
          exclude: |
            **/.git*
            **/.git*/**
            **/README.md